name: rebuy-pub-ds-utils
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - scikit-learn
  - pandas
  - numpy
  - matplotlib
  - pytest=3.1.2
  - ghp-import
  # - jupyter
  # - ipython
# Include pip based packages
  # - pip:
  #   - sklearn-pandas
  #   - imbalanced-learn
